name: Discord notification
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Any Name Bash Test Step
      shell: bash
      run: |
          echo "DISCORD_WEBHOOK: $DISCORD_WEBHOOK"
      env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
    - name: send message
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@master
      with:
        args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} has been deployed.'
